language: python
python:
  - "3.5"
  - "3.6"
env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1
install:
  - pip install pipenv
  - pipenv install --dev
script:
  - pipenv run mypy --ignore-missing-imports --strict-optional --check-untyped-defs british_food_generator/
