language: python
python:
  - "3.8"
  - "3.9-dev"
matrix:
  allow_failures:
    - python: "3.9-dev"
env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1
install:
  - pip install pipenv
  - pipenv install --dev
script:
  - ./test.sh
